package com.provisiones.types.informes;

public class PresupuestoInforme 
{
	private String PROPIETARIO_DEFINITIVO = "";
	private String PROPIETARIO_ACTUAL = "";
	private String PROPIETARIO_ORIGEN = "";
	private String ACTIVO = "";
	private String PROVINCIA = "";
	private String CP = "";
	private String POBLACION = "";
	private String GESTORIA = "";
	private String PRESUPUESTO_COMUNIDADES = "";
	private String IMPORTE_TOTAL_PAGADO_COMUNIDAD = "";
	private String IMPORTE_PENDIENTE_COMUNIDAD = "";
	private String IMPORTE_LIBERADO_COMUNIDAD = "";
	private String OBSERVACIONES_COMUNIDAD = "";
	private String PRESUPUESTO_TRIBUTOS = "";
	private String IMPORTE_TOTAL_PAGADO_TRIBUTOS = "";
	private String IMPORTE_PENDIENTE_TRIBUTOS = "";
	private String IMPORTE_LIBERADO_TRIBUTOS = "";
	private String OBSERVACIONES_TRIBUTOS = "";
	private String COMENTARIOS = "";

	//Constructor de clase
	
	public PresupuestoInforme(String pROPIETARIO_DEFINITIVO,
			String pROPIETARIO_ACTUAL, String pROPIETARIO_ORIGEN,
			String aCTIVO, String pROVINCIA, String cP, String pOBLACION,
			String gESTORIA, String pRESUPUESTO_COMUNIDADES,
			String iMPORTE_TOTAL_PAGADO_COMUNIDAD,
			String iMPORTE_PENDIENTE_COMUNIDAD,
			String iMPORTE_LIBERADO_COMUNIDAD, String oBSERVACIONES_COMUNIDAD,
			String pRESUPUESTO_TRIBUTOS, String iMPORTE_TOTAL_PAGADO_TRIBUTOS,
			String iMPORTE_PENDIENTE_TRIBUTOS,
			String iMPORTE_LIBERADO_TRIBUTOS, String oBSERVACIONES_TRIBUTOS,
			String cOMENTARIOS) {
		super();
		PROPIETARIO_DEFINITIVO = pROPIETARIO_DEFINITIVO;
		PROPIETARIO_ACTUAL = pROPIETARIO_ACTUAL;
		PROPIETARIO_ORIGEN = pROPIETARIO_ORIGEN;
		ACTIVO = aCTIVO;
		PROVINCIA = pROVINCIA;
		CP = cP;
		POBLACION = pOBLACION;
		GESTORIA = gESTORIA;
		PRESUPUESTO_COMUNIDADES = pRESUPUESTO_COMUNIDADES;
		IMPORTE_TOTAL_PAGADO_COMUNIDAD = iMPORTE_TOTAL_PAGADO_COMUNIDAD;
		IMPORTE_PENDIENTE_COMUNIDAD = iMPORTE_PENDIENTE_COMUNIDAD;
		IMPORTE_LIBERADO_COMUNIDAD = iMPORTE_LIBERADO_COMUNIDAD;
		OBSERVACIONES_COMUNIDAD = oBSERVACIONES_COMUNIDAD;
		PRESUPUESTO_TRIBUTOS = pRESUPUESTO_TRIBUTOS;
		IMPORTE_TOTAL_PAGADO_TRIBUTOS = iMPORTE_TOTAL_PAGADO_TRIBUTOS;
		IMPORTE_PENDIENTE_TRIBUTOS = iMPORTE_PENDIENTE_TRIBUTOS;
		IMPORTE_LIBERADO_TRIBUTOS = iMPORTE_LIBERADO_TRIBUTOS;
		OBSERVACIONES_TRIBUTOS = oBSERVACIONES_TRIBUTOS;
		COMENTARIOS = cOMENTARIOS;
	}
	
	//Métodos de acceso

	public String getPROPIETARIO_DEFINITIVO() {
		return PROPIETARIO_DEFINITIVO;
	}

	public void setPROPIETARIO_DEFINITIVO(String pROPIETARIO_DEFINITIVO) {
		PROPIETARIO_DEFINITIVO = pROPIETARIO_DEFINITIVO;
	}

	public String getPROPIETARIO_ACTUAL() {
		return PROPIETARIO_ACTUAL;
	}

	public void setPROPIETARIO_ACTUAL(String pROPIETARIO_ACTUAL) {
		PROPIETARIO_ACTUAL = pROPIETARIO_ACTUAL;
	}

	public String getPROPIETARIO_ORIGEN() {
		return PROPIETARIO_ORIGEN;
	}

	public void setPROPIETARIO_ORIGEN(String pROPIETARIO_ORIGEN) {
		PROPIETARIO_ORIGEN = pROPIETARIO_ORIGEN;
	}

	public String getACTIVO() {
		return ACTIVO;
	}

	public void setACTIVO(String aCTIVO) {
		ACTIVO = aCTIVO;
	}

	public String getPROVINCIA() {
		return PROVINCIA;
	}

	public void setPROVINCIA(String pROVINCIA) {
		PROVINCIA = pROVINCIA;
	}

	public String getCP() {
		return CP;
	}

	public void setCP(String cP) {
		CP = cP;
	}

	public String getPOBLACION() {
		return POBLACION;
	}

	public void setPOBLACION(String pOBLACION) {
		POBLACION = pOBLACION;
	}

	public String getGESTORIA() {
		return GESTORIA;
	}

	public void setGESTORIA(String gESTORIA) {
		GESTORIA = gESTORIA;
	}

	public String getPRESUPUESTO_COMUNIDADES() {
		return PRESUPUESTO_COMUNIDADES;
	}

	public void setPRESUPUESTO_COMUNIDADES(String pRESUPUESTO_COMUNIDADES) {
		PRESUPUESTO_COMUNIDADES = pRESUPUESTO_COMUNIDADES;
	}

	public String getIMPORTE_TOTAL_PAGADO_COMUNIDAD() {
		return IMPORTE_TOTAL_PAGADO_COMUNIDAD;
	}

	public void setIMPORTE_TOTAL_PAGADO_COMUNIDAD(
			String iMPORTE_TOTAL_PAGADO_COMUNIDAD) {
		IMPORTE_TOTAL_PAGADO_COMUNIDAD = iMPORTE_TOTAL_PAGADO_COMUNIDAD;
	}

	public String getIMPORTE_PENDIENTE_COMUNIDAD() {
		return IMPORTE_PENDIENTE_COMUNIDAD;
	}

	public void setIMPORTE_PENDIENTE_COMUNIDAD(String iMPORTE_PENDIENTE_COMUNIDAD) {
		IMPORTE_PENDIENTE_COMUNIDAD = iMPORTE_PENDIENTE_COMUNIDAD;
	}

	public String getIMPORTE_LIBERADO_COMUNIDAD() {
		return IMPORTE_LIBERADO_COMUNIDAD;
	}

	public void setIMPORTE_LIBERADO_COMUNIDAD(String iMPORTE_LIBERADO_COMUNIDAD) {
		IMPORTE_LIBERADO_COMUNIDAD = iMPORTE_LIBERADO_COMUNIDAD;
	}

	public String getOBSERVACIONES_COMUNIDAD() {
		return OBSERVACIONES_COMUNIDAD;
	}

	public void setOBSERVACIONES_COMUNIDAD(String oBSERVACIONES_COMUNIDAD) {
		OBSERVACIONES_COMUNIDAD = oBSERVACIONES_COMUNIDAD;
	}

	public String getPRESUPUESTO_TRIBUTOS() {
		return PRESUPUESTO_TRIBUTOS;
	}

	public void setPRESUPUESTO_TRIBUTOS(String pRESUPUESTO_TRIBUTOS) {
		PRESUPUESTO_TRIBUTOS = pRESUPUESTO_TRIBUTOS;
	}

	public String getIMPORTE_TOTAL_PAGADO_TRIBUTOS() {
		return IMPORTE_TOTAL_PAGADO_TRIBUTOS;
	}

	public void setIMPORTE_TOTAL_PAGADO_TRIBUTOS(
			String iMPORTE_TOTAL_PAGADO_TRIBUTOS) {
		IMPORTE_TOTAL_PAGADO_TRIBUTOS = iMPORTE_TOTAL_PAGADO_TRIBUTOS;
	}

	public String getIMPORTE_PENDIENTE_TRIBUTOS() {
		return IMPORTE_PENDIENTE_TRIBUTOS;
	}

	public void setIMPORTE_PENDIENTE_TRIBUTOS(String iMPORTE_PENDIENTE_TRIBUTOS) {
		IMPORTE_PENDIENTE_TRIBUTOS = iMPORTE_PENDIENTE_TRIBUTOS;
	}

	public String getIMPORTE_LIBERADO_TRIBUTOS() {
		return IMPORTE_LIBERADO_TRIBUTOS;
	}

	public void setIMPORTE_LIBERADO_TRIBUTOS(String iMPORTE_LIBERADO_TRIBUTOS) {
		IMPORTE_LIBERADO_TRIBUTOS = iMPORTE_LIBERADO_TRIBUTOS;
	}

	public String getOBSERVACIONES_TRIBUTOS() {
		return OBSERVACIONES_TRIBUTOS;
	}

	public void setOBSERVACIONES_TRIBUTOS(String oBSERVACIONES_TRIBUTOS) {
		OBSERVACIONES_TRIBUTOS = oBSERVACIONES_TRIBUTOS;
	}

	public String getCOMENTARIOS() {
		return COMENTARIOS;
	}

	public void setCOMENTARIOS(String cOMENTARIOS) {
		COMENTARIOS = cOMENTARIOS;
	}
	
}
